2022-05-31 23:13:08 bank_transaction root.__init__ +41: INFO [86453] Customer Account Exists
2022-05-31 23:13:08 bank_transaction root.deposit_amount +89: INFO [86453] Deposit Successful. Inserted Rowcount:2
2022-05-31 23:18:40 bank_transaction root.__init__ +41: INFO [86753] New Account should be Created
2022-05-31 23:18:40 bank_transaction root.deposit_amount +89: INFO [86753] Deposit Successful. Inserted Rowcount:2
2022-05-31 23:47:08 bank_transaction root.__init__ +41: INFO [88306] New Account should be Created
2022-05-31 23:47:08 bank_transaction root.withdraw_amount +107: INFO [88306] Withdraw Successful. Inserted Rowcount:2
2022-05-31 23:47:08 bank_transaction root.withdraw_amount +113: ERROR [88306] 'BankTransaction' object has no attribute 'amount'
Traceback (most recent call last):
  File "bank_transaction.py", line 108, in withdraw_amount
    print(f"${self.amount} Withdrawn from account {self.account_id}")
AttributeError: 'BankTransaction' object has no attribute 'amount'
2022-05-31 23:48:02 bank_transaction root.__init__ +41: INFO [88387] New Account should be Created
2022-05-31 23:48:02 bank_transaction root.withdraw_amount +107: INFO [88387] Withdraw Successful. Inserted Rowcount:2
